name: "Pack fr-FR - Static Analysis"

on:
  schedule:
    - cron: "42 3 * * 1"
  push:
    paths:
      - .github/workflows/pack-fr-fr-continuous-integration.yml

jobs:
  phpstan:
    name: "Static Analysis"
    runs-on: "ubuntu-22.04"

    strategy:
      matrix:
        php-version:
          - "8.2"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 'DbToolsBundle/pack-fr-fr'

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: cs2pr

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Run static analysis with phpstan/phpstan
        run: vendor/bin/phpstan --error-format=checkstyle | cs2pr
